name: generate ascii artwork
on: push
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Sleep for 30 seconds
        run: sleep 30
  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
        - name: execute cowsay cmd
          run: cowsay -f dragon "Run for a cover , I am a dragon" >> dragon.txt 

        - name: Test file exists
          run: grep -i "dragon" dragon.txt
  job_3:
    needs: job_2
    runs-on: ubuntu-latest
    steps:
        - name: Read file
          run: cat dragon.txt

        - name: checkout repo file
          run: ls


      