name: first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v4

            - name: welcome message
              run: | 
                echo "my first github actions workflow"
                ls -ltra
                cat README.md

            # - name: list files
            #   run: ls

            # - name: read file
            #   run: cat README.md

            
